server:
  port: 8086
eureka:
  client:
    register-with-eureka: false
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/


