server:
  port: 8001

#服务名称
spring:
  application:
    name: cloud-payment-service

eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: false
    # 入驻地址
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5 # eureka客户端向服务端发送心跳的时间间隔 单位秒 默认30
    lease-expiration-duration-in-seconds: 10 # eureka